spring.datasource.url=jdbc:mysql://localhost:3306/dbPedido?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=GMT
spring.jpa.hibernate.ddl-auto=create
spring.datasource.username=root
spring.datasource.password=
